# -*- coding: utf-8 -*-
# Author: Hugo Ochoa <hugo@stateoftheart.ai>
# Copyright: Stateoftheart AI PBC 2020.
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
repos:
  # General hooks:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=3000"]
  # Python Google Official Guideline hooks:
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        entry: ./.venv/bin/pylint
  - repo: git@github.com:pre-commit/mirrors-yapf.git
    rev: v0.26.0
    hooks:
      - id: yapf
        entry: ./.venv/bin/yapf
        args: ["--style=.style.yapf", "--parallel", "--in-place"]
