name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install sotaai Library & Dependencies
        run: |
          python -m pip install pip==19.2.3
          pip install -e .
      - name: Run tests
        run: |
          cd tests
          python -m unittest
